name: master
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - run: sudo apt-get upgrade && sudo apt-get update
    - run: sudo apt-get install python-pygame -y --fix-missing
    - run: python -m pip install -r requirements.txt
    - run: pytest --cov-report=xml --cov=src/
    - run: codecov
